### ISSUE TITLE
Cant export RGA

### ISSUE THREAD

**Issue by Nazarus13** [SiMaLaoShi/AssetStudio_Tuanjie#4]
[D.zip](https://github.com/user-attachments/files/17180901/D.zip)
Hello, cant export tga files MRAO/Normal maps. What the problem it could be?
![изображение](https://github.com/user-attachments/assets/5d8c64de-8c68-403c-bd77-fc7745b391c1)

**Comment by SiMaLaoShi** [comment]
![image](https://github.com/user-attachments/assets/43b64a1b-978f-487d-bd39-777183668486)
Hello, your example can be derived

**Comment by SiMaLaoShi** [comment]
Sorry about that

**Comment by SiMaLaoShi** [comment]
Can you provide your normal map
![image](https://github.com/user-attachments/assets/5450089b-e1a7-4407-af89-cb1d9dfdd90a)
I've got a normal map here that shows it

**Comment by SiMaLaoShi** [comment]
Normal mapping is not supported, I will study it later

**Comment by aelurum** [comment]
It's just a bug with Texture2D parsing for Unity version 2022.2+ (and Tuanjie as well)
There should be a stream align after the `m_IgnoreMipmapLimit` field *(or before the `m_MipmapLimitGroupName`)*

**Comment by SiMaLaoShi** [comment]
> `m_IgnoreMipmapLimit`

你那边的库有修复吗

**Comment by SiMaLaoShi** [comment]
> It's just a bug with Texture2D parsing for Unity version 2022.2+ (and Tuanjie as well) There should be a stream align after the `m_IgnoreMipmapLimit` field _(or before the `m_MipmapLimitGroupName`)_

看了一下这个两个字段好像2019上的版本都有了，应该不是这个，我这边看了一下NormalMap类型的最开始的AssetStudio版本都没做解析，字段内容有点多
![image](https://github.com/user-attachments/assets/49d95d3b-f6d0-464f-b1e8-9410c216c045)

**Comment by SiMaLaoShi** [comment]
> [D.zip](https://github.com/user-attachments/files/17180901/D.zip) Hello, cant export tga files MRAO/Normal maps. What the problem it could be? ![изображение](https://private-user-images.githubusercontent.com/69793579/371886006-5d8c64de-8c68-403c-bd77-fc7745b391c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzY4MTUsIm5iZiI6MTcyODg3NjUxNSwicGF0aCI6Ii82OTc5MzU3OS8zNzE4ODYwMDYtNWQ4YzY0ZGUtOGM2OC00MDNjLWJkNzctZmM3NzQ1YjM5MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2UxOTE2ZmQwY2E3NzU2OTUyNWM2NGNjZTk0ZDFmYTVkNTkzY2I0ODkzYWM3NjJiMDYyMDIyN2RmYThkYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8dJaf-L5Ku9_k9FXqLIeLC1IZoGJYlonV0Gb8wZa31w)

![image](https://github.com/user-attachments/assets/f5279b0c-8906-420a-bef7-e00240408746)
Fixed, please use the latest version

**Comment by aelurum** [comment]
> 你那边的库有修复吗

Yes

The `m_IgnoreMasterTextureLimit` field was added in v2019.3, yeah
But was replaced with 2 new fields `m_IgnoreMipmapLimit` and `m_MipmapLimitGroupName` in v2022.2+
And there should be a stream alignment between them
![image](https://github.com/user-attachments/assets/60b49beb-847d-439e-aebd-6a52e967f5df)
(src: https://github.com/AssetRipper/TypeTreeDumps/tree/main/StructsDump/release)

For example, your current fix will not work for a texture that actually contains MipmapLimitGroupName
[m_MipmapLimitGroupName_2022.2.16f1.zip](https://github.com/user-attachments/files/17365691/m_MipmapLimitGroupName_2022.2.16f1.zip)

Also, with the alignment fix you don't need the workaround for v2022.3.2t13+ https://github.com/SiMaLaoShi/AssetStudio_Tuanjie/blob/7a9f1be4cdbfdfa1bcb8944f9e51ec769ee68ee8/AssetStudio/Classes/Texture2D.cs#L169-L174
Because v2022.3.2t13 also uses `m_PlatformBlob` as well as previous versions of Tuanjie 👀

**Comment by SiMaLaoShi** [comment]
> > 你那边的库有修复吗
> 
> Yes
> 
> The `m_IgnoreMasterTextureLimit` field was added in v2019.3, yeah But was replaced with 2 new fields `m_IgnoreMipmapLimit` and `m_MipmapLimitGroupName` in v2022.2+ And there should be a stream alignment between them ![image](https://private-user-images.githubusercontent.com/6244109/376153968-60b49beb-847d-439e-aebd-6a52e967f5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjA4MjUsIm5iZiI6MTcyODk2MDUyNSwicGF0aCI6Ii82MjQ0MTA5LzM3NjE1Mzk2OC02MGI0OWJlYi04NDdkLTQzOWUtYWViZC02YTUyZTk2N2Y1ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDI0ODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRjM2ZlMDNjYTg1MDZjNzJjNjIzZWFmNzc4MjM3ZWZhM2Y1MzI1Yjc5NzU5ZDE1NDE0M2MzMzkwZmJhMGRlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aSNLunE_9cWuYsdBHJzZlua_nELGa2lpnkl6WepTimE) (src: https://github.com/AssetRipper/TypeTreeDumps/tree/main/StructsDump/release)
> 
> For example, your current fix will not work for a texture that actually contains MipmapLimitGroupName [m_MipmapLimitGroupName_2022.2.16f1.zip](https://github.com/user-attachments/files/17365691/m_MipmapLimitGroupName_2022.2.16f1.zip)
> 
> Also, with the alignment fix you don't need the workaround for v2022.3.2t13+
> 
> https://github.com/SiMaLaoShi/AssetStudio_Tuanjie/blob/7a9f1be4cdbfdfa1bcb8944f9e51ec769ee68ee8/AssetStudio/Classes/Texture2D.cs#L169-L174
> 
> 
> Because v2022.3.2t13 also uses `m_PlatformBlob` as well as previous versions of Tuanjie 👀
thanks
